### ISSUE TITLE
authorized_keys are overwritten by coreos

### ISSUE THREAD

**Issue by philhug** [ppschweiz/pps-infra#20]
coreos uses update-ssh-keys to generate authorized_keys file from authorized_keys.d directory.
make sure this plays well with our ansible deployment.

**Comment by cambid** [comment]
@cambid: Setting the path parameter in the module authorized_key should work.

**Comment by J0WI** [comment]
Still an issue for me

**Comment by cambid** [comment]
If retested it with update-ssh-keys. The keys from the directory have got successfully written to the authorized_keys-file.
